/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetRouteImport } from './routes/widget'
import { Route as ApiTidesRouteImport } from './routes/api/tides'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetRoute = WidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTidesRoute = ApiTidesRouteImport.update({
  id: '/api/tides',
  path: '/api/tides',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/widget': typeof WidgetRoute
  '/api/tides': typeof ApiTidesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/widget': typeof WidgetRoute
  '/api/tides': typeof ApiTidesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/widget': typeof WidgetRoute
  '/api/tides': typeof ApiTidesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/widget' | '/api/tides'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/widget' | '/api/tides'
  id: '__root__' | '/' | '/widget' | '/api/tides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WidgetRoute: typeof WidgetRoute
  ApiTidesRoute: typeof ApiTidesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget': {
      id: '/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof WidgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tides': {
      id: '/api/tides'
      path: '/api/tides'
      fullPath: '/api/tides'
      preLoaderRoute: typeof ApiTidesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WidgetRoute: WidgetRoute,
  ApiTidesRoute: ApiTidesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
